### ISSUE TITLE
Throw for wrong mode usage

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#78] opened 2015-07-31 21:04 UTC
Now for template
```js
block('b1')(
   mix({ elem: 'e1' }) // should be mix()({ elem: 'e1' })
);
```
nothing is happen and it's quite hard to understand what's wrong with the code.

**Comment by indutny** [comment] 2015-08-03 20:02
Duplicate of https://github.com/bem/bem-xjst/issues/49

**Closed by indutny** 2015-08-03 20:02 UTC
Labels: enhancement
