### ISSUE TITLE
Runtime fails after minification

### ISSUE THREAD

**Issue by sbmaxx** [bem/bem-xjst#116] opened 2015-11-02 07:18 UTC
Not sure about placing bug here. Maybe it related to `enb-borschik, enb-bemxjst`.

Repo is the same, added another test for new bug — https://github.yandex-team.ru/sbmaxx/bemhtml-bug

After using `enb-borschik` for `index.bemhtml.js` runtime stop working. It fails with just one `bemhtml.js` file:
```js
block('foo').tag()('span');
```

**Error**:
```
     ReferenceError: r is not defined
      at Object.eval (eval at <anonymous> (desktop.bundles/index/_index.bemhtml.js:1:6058), <anonymous>:3:1)
      at d.build (desktop.bundles/index/_index.bemhtml.js:1:18296)
      at i.compile (desktop.bundles/index/_index.bemhtml.js:1:5528)
      at e (desktop.bundles/index/_index.bemhtml.js:1:21965)
      at desktop.bundles/index/_index.bemhtml.js:1:22246
      at Object.<anonymous> (desktop.bundles/index/_index.bemhtml.js:1:22372)
      at Context.<anonymous> (test/test.js:35:20)
```

@tadatuta @arikon @indutny @veged

**Comment by sbmaxx** [comment] 2015-11-02 07:38
It fails on `recompileInput`.

Before recompile we have templates:
```js
function (t, e, n, s, r, o, h, c, u, l, a, p, f, d, m, y, v, b, x, g, k) {
                r("foo").tag()("span"), k(function(t, e) {
                    var n = t.BEMContext || e.BEMContext;
                    n.prototype.require = function(t) {
                        return i[t]
                    }
                })
            }
```
And after:
```js
function(match, once, wrap, elemMatch, block, elem, mode, mod, elemMod, def, tag, attrs, cls, js, jsAttr, bem, mix, content, replace, extend, oninit, xjstOptions, local, applyCtx, applyNext, apply) {
                r("foo").tag()("span"), k(function(t, e) {
                    var n = t.BEMContext || e.BEMContext;
                    n.prototype.require = function(t) {
                        return i[t]
                    }
                })
            }
```

All variables replaced with unminimized version.Why do we need this recompile?

**Comment by tadatuta** [comment] 2015-11-02 08:10
Looks like a duplicate of https://github.com/bem/bem-xjst/issues/101

**Comment by mishanga** [comment] 2015-11-02 08:45
да, это дубликат #101

**Closed by mishanga** 2015-11-02 08:45 UTC
